### ISSUE TITLE
EVM link in index.html doesn't work properly

### ISSUE THREAD

**Issue by ctharvey** [Web3Modal/web3modal-vanilla-js-example#8]
Causes example to fail if git is cloned.  Resolved by replacing:

`<script type="text/javascript" src="https://unpkg.com/evm-chains/lib/index.js"></script>`

with 

`<script type="text/javascript" src="https://unpkg.com/evm-chains@0.2.0/dist/umd/index.min.js"></script>`

**Comment by pedrouid** [comment]
Thanks for pointing it out! 🙌 Fixed on commit https://github.com/Web3Modal/web3modal-vanilla-js-example/commit/97fc9211c9057d8a3e15df7a55b9a5240b19c263
